{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ $name }}
spec:
  type: {{ default "ClusterIP" $svc.service.type }}
  selector:
    app: {{ $.Chart.Name }}-{{ $name }}
  ports:
    - port: {{ default 8000 $svc.service.port }}
      targetPort: {{ default 8000 $svc.containerPort }}
---
{{- end }}
{{- end }}
