apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-drawing-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}-drawing-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
